# Imports from Django
from django.conf.urls.defaults import *


urlpatterns = patterns('brubeck.events.views',
    url(r'^(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/(?P<event_slug>[-\w]+)/$', 'event_detail', name='calendar-event-detail'),
    (r'^(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/p(?P<page>\d+)/$', 'event_list'),
    (r'^(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/$', 'event_list'),
    (r'^(?P<year>\d{4})/(?P<month>\w{1,2})/p(?P<page>\d+)/$', 'event_list'),
    (r'^(?P<year>\d{4})/(?P<month>\w{1,2})/$', 'event_list'),
    (r'^(?P<year>\d{4})/p(?P<page>\d+)/$', 'event_list'),
    (r'^(?P<year>\d{4})/$', 'event_list'),
    (r'^p(?P<page>\d+)/$', 'event_list'),
    (r'^(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/(?P<event_slug>[-\w]+)/$', 'event_detail'),
    (r'^(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/p(?P<page>\d+)/$', 'event_list'),
    (r'^(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/$', 'event_list'),
    (r'^(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\w{1,2})/p(?P<page>\d+)/$', 'event_list'),
    (r'^(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\w{1,2})/$', 'event_list'),
    (r'^(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/p(?P<page>\d+)/$', 'event_list'),
    (r'^(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/$', 'event_list'),
    (r'^(?P<calendar_slug>[-\w]+)/p(?P<page>\d+)/$', 'event_list'),
    (r'^test/all/$', 'grid_one'),
    (r'^test/(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/(?P<month>\w{1,2})/$', 'grid_one'),
    (r'^test/(?P<calendar_slug>[-\w]+)/(?P<year>\d{4})/$', 'grid_one'),
    (r'^test/(?P<calendar_slug>[-\w]+)/$', 'grid_one'),
    (r'^test/all/(?P<year>\d{4})/(?P<month>\w{1,2})/$', 'grid_one'),
    (r'^test/all/(?P<year>\d{4})/$', 'grid_one'),
    (r'^test/all/$', 'grid_one'),
    url(r'^(?P<calendar_slug>[-\w]+)/page/(?P<page>\d+)/$', 'event_list', name='calendar-calendar-detail'),    
    url(r'^(?P<calendar_slug>[-\w]+)/$', 'event_list', name='calendar-calendar-detail'),
    (r'^page/(?P<page>\d+)/$', 'event_list'),    
    (r'^$', 'event_list'),
)
